### ISSUE TITLE
Problem loading integration_paperless-settings.js

### ISSUE THREAD

**Issue by pkrolkgp** [nextcloud/integration_paperless#34]
I have this error when trying to setup installed integration when i go to setup and click Settings->Connected Accounts

` {"reqId":"ia9iHzNphPYwbYO1g7QS","level":3,"time":"2024-08-26T11:29:02+00:00","remoteAddr":"xx.x.x.xxx","user":"Keycloak-XXXXXX","app":"jsresourceloader","method":"GET","url":"/settings/user/connected-accounts","message":"Could not find resource integration_paperless/js/integration_paperless-settings.js to load","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0","version":"29.0.5.1","data":{"app":"jsresourceloader"}}`

It displays blank settings.
When i right click on file nothing shows for integration

**Comment by provokateurin** [comment]
The file is present in the release tarball. Can you make sure it exists in your installation? It should be present at `apps/integration_paperless/js/integration_paperless-settings.js` (or in a different apps folder depending on your config.

**Comment by pkrolkgp** [comment]
There is no file named `integration_paperless-settings.js` anywhere in any tarball.
There is only `settings.js` in `src `folder wich is linked in file `webpack.js` in line 8. 
But it's not working

**Comment by provokateurin** [comment]
I checked it myself by downloading the latest release from https://apps.nextcloud.com/apps/integration_paperless which points to the tarball of https://github.com/nextcloud-releases/integration_paperless/releases/tag/v1.0.3 and that includes the file as expected.
Are you maybe confusing this with the download option Github provides (https://github.com/nextcloud/integration_paperless/archive/refs/heads/main.zip)? That link is for downloading the source code which does not include the js file because it has to be compiled first. It only includes the src/settings.js you mentioned. The whole src folder does not even exist in the release tarball.

**Comment by pkrolkgp** [comment]
I was, yes.
